# Generated by Django 3.2 on 2021-05-19 04:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittercloneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='body',
            field=models.CharField(db_index=True, default='', max_length=140, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created Datetime'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Like Count'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Datetime'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name'),
        ),
    ]
