# Generated by Django 3.2 on 2021-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittercloneapp', '0002_auto_20210519_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.CharField(db_index=True, default='Anonymous', max_length=1000, verbose_name='image'),
        ),
    ]
